language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: npm
  email: jason.p.pickering@gmail.com
  api_key:
    secure: UgLqEzpxsv5BAgG/Xt3lv+Me0hsPzDJ3E2kINh4jBvq5e0f3gwAFNve0NnwZvc1bxrv97e5SlE0IVCoF6AGIKBGhqTi4aFTZapCKnHO+pBMQ6rp06pS2tEd58LyWP2XNA4lyFwMTzXdQxfVHqtR0qBG7oMWF8oc+vGLOkl0kHsXo23ynpnXoaQaAYTspWH7aVwCxCF3mH7Di6Y4jxWAO5O03PZzkjyNFgOYesAm7GwVl1eBct0nEf4IRwaxRl7CCD95fLeKd+MVhO9jWQOWVhorHZHNOMgTqPxe14eOHxbO1Dy8xyz1eeR1Y3vb0QKA0VVj8mtNda51TTWRl8rFo/Ab/5z4Fy9MwshLZnkfWZt3YwCUdrS2wUhQhwbOcL5Auuh3oBe0dKKKc2NRZZWQGdxoqDumSCgp6B83JDa+cXNdX77xzhRQ+V++wFlVWMuO+nlMXPVAdctsz5YMfSMsnZ9n/cQKO8J8EtdqZ36UY6C71WxEY2TNkkX6p+3wELauxUXPLw4Tar9teHwFOhlIhrlNxZgLvbZB8ciEBPqh/vIlXLAKvgJDnE07h8ZdOE7GQuyFVn75a5CfSAhuqMn2tVXA1SWYYLBPLFXblUgtVyiLhbXMkBSBOiVw2QSLFq7UgqMvkLulKxInTv5VTPNZB1wRfMWpt2Yb6VvOiNWNAoLw=
  on:
    tags: true
  skip_cleanup: true
notifications:
  slack:
    secure: dG1I0Vw+TxvfVu6EPnMcsPRCeEWZmN0972jTQ224tov6sqWfTDPtRNj9WP1VuB51+88zuZZlvRnLTE3fGSvke1iT8yjcSwHjP0qZQ1EcdbEhsaQKWBNC9gQVN55hUFMxzZAz8pRhr9HwBt2SaFWcMZBkvofpXGPu+176jR4O/8bFCZi8oj1/P2uoeOitTevminUZK//O7OqcWWfe9C693jeakNAzio1AVMOAky5gaUp+IM9VHJHMCrBj+StZs+V3ocELksD16Yra8Ezj67xZL6c+Mivnl1MZdgkkTpZi77yC+NuHTU4SDLhz6JjQen0bPkgAcRRoO5H0jBGB74ZlyF6PpK6LAye3joATMaBqQWakt0eid6iqI6v2U4BaBpTTQNLFhERZgvW6oe6FFMGpIpXbIM+ru+DuHoNNuVt3UVSJB5txJGtp6HXaUfbY1nzv7xiovnLXmtHgQYWZcQOly/mf/RRcWnJPNA1lflwdadLwJ4SGXG1zWeZTUU+C+EX4vYLock+Ifk+fSeJEnVLMVZvTkEjNOjU0G0RMXgj8BEgycUjv/aoz7S+Qtiwes0fk27Ec8bCKGabtwjtPS6I3zmgvxkNiGQGEaMsNdL5xQFGGqAuk4zRqcP+etRm00vR5Gql7l38rFUCs3q4RFwKUK51s9J8E12aEX+Btja9jAIo=
